package com.hendraanggrian.prefy.internal

import com.hendraanggrian.prefy.EditablePreferences
import com.hendraanggrian.prefy.PreferencesEditor
import com.hendraanggrian.prefy.PreferencesSaver
import com.hendraanggrian.prefy.ReadablePreferences
import com.hendraanggrian.prefy.WritablePreferences

/**
 * Parent class of any class generated by `local-compiler` (should they are being used in the project).
 * It behaves similarly as [ReadablePreferences] with simpler API for generated sources to use.
 */
abstract class PreferencesBinding(private val source: ReadablePreferences) : PreferencesSaver {

    protected fun get(key: String, defaultValue: String?): String? = source[key] ?: defaultValue
    protected fun get(key: String, defaultValue: Boolean): Boolean = source.getBoolean(key) ?: defaultValue
    protected fun get(key: String, defaultValue: Double): Double = source.getDouble(key) ?: defaultValue
    protected fun get(key: String, defaultValue: Float): Float = source.getFloat(key) ?: defaultValue
    protected fun get(key: String, defaultValue: Long): Long = source.getLong(key) ?: defaultValue
    protected fun get(key: String, defaultValue: Int): Int = source.getInt(key) ?: defaultValue
    protected fun get(key: String, defaultValue: Short): Short = source.getShort(key) ?: defaultValue
    protected fun get(key: String, defaultValue: Byte): Byte = source.getByte(key) ?: defaultValue

    protected val editor: PreferencesEditor
        get() = when (source) {
            is WritablePreferences -> source
            is EditablePreferences<*> -> source.editor
            else -> error("Unrecognizable preferences instance")
        }
}
