const val RELEASE_USER = "hendraanggrian"
const val RELEASE_ARTIFACT = "prefy"
const val RELEASE_GROUP = "com.$RELEASE_USER.$RELEASE_ARTIFACT"
const val RELEASE_VERSION = "0.2"
const val RELEASE_DESC = "Local settings library with emphasis on Kotlin"
const val RELEASE_WEB= "https://github.com/$RELEASE_USER/$RELEASE_ARTIFACT"
